all:
  children:
    nginx:
      hosts:
        nginx-dev:
          ansible_host: "{{ nginx_hosts.dev.ip }}"
          cert_name: hdc-dev
          domains:
            - dev.hdc.ebrains.eu
            - argocd.dev.hdc.ebrains.eu
        nginx-prod:
          ansible_host: "{{ nginx_hosts.prod.ip }}"
          cert_name: hdc-prod
          domains:
            - hdc.ebrains.eu
  vars:
    ansible_port: "{{ ssh_port | default(target_ssh_port) }}"
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"
